{
    "name": "HomeBlend Reports",
    "version": "19.0.1.10.0",
    "category": "Productivity",
    "summary": "تقارير المستأجرين والعمولات والمبيعات والمشاريع",
    "author": "HomeBlend",
    "license": "LGPL-3",
    "depends": [
        "homeblend_tenant",
        "homeblend_fulfillment",
        "artcasa_operations",
        "homeblend_hr_payroll",
        "sale_stock",
        "account",
        "analytic",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/reports_security.xml",
        "views/report_views.xml",
        "views/asset_views.xml",
        "views/financial_views.xml",
        "data/asset_data.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": True,
}
