{
    "name": "Art Casa Operations",
    "version": "19.0.1.13.0",
    "category": "Sales",
    "summary": "تقسيم الفاتورة، الربح بعد التكاليف الإضافية، وحجز مخزون المندوب",
    "author": "HomeBlend",
    "license": "LGPL-3",
    "depends": [
        "homeblend_base",
        "sale_management",
        "sale_project",
        "sale_margin",
        "barcodes",
        "sale_stock",
        "stock",
        "stock_landed_costs",
        "purchase",
        "purchase_requisition",
        "account",
        "mail",
        "analytic",
        "product_expiry",
        "point_of_sale",
        "sale_loyalty",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/reservation_security.xml",
        "data/reservation_data.xml",
        "views/project_views.xml",
        "views/product_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/reservation_views.xml",
        "views/barcode_views.xml",
        "views/res_partner_views.xml",
        "views/collection_views.xml",
        "views/report_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": True,
}
