from . import project_project
from . import product_template
from . import product_product
from . import barcode_inventory
from . import sale_order
from . import account_move
from . import stock_reservation
from . import stock_orderpoint
from . import res_company
from . import res_partner
